# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: /usr/bin/google-chrome-stable
          key: ${{ runner.os }}-chrome

      - name: Install Chrome
        if: steps.cache-chrome.outputs.cache-hit != 'true'
        id: install-chrome
        run: |
          sudo apt-get install libxss1 libappindicator1 libindicator7
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome*.deb
          echo "$(which google-chrome-stable)"

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 10.x

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Unit / Integration Tests
        run: yarn test

      - name: Browser Tests
        run: yarn browser-test
